// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { ResponseItemMetadata } from "./ResponseItemMetadata";

export type InterAgentCommunication = { author: AgentPath, recipient: AgentPath, other_recipients: Array<AgentPath>, content: string, encrypted_content?: string, metadata?: ResponseItemMetadata, trigger_turn: boolean, };
